<?php
/**
 * @version		$Id: notify.php 07/10/2017 wrparker $
 * @package		Joomla
 * @subpackage	Content
 * @copyright	Copyright (C) 2005 - 2008 Open Source Matters. All rights reserved.
 * @license		GNU/GPL, see LICENSE.php
 * Joomla! is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 * See COPYRIGHT.php for copyright notices and details.
 */
 
 // no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
//jimport('joomla.plugin.plugin');

class plgContentNotify extends JPlugin {
       //protected $autoloadLanguage = true;
    function onContentAfterSave($context, $article, $isNew) {
        $config = JFactory::getConfig();
        $user =& JFactory::getUser();   
        

        $title = $article->title;       
        $uri = & JFactory::getURI(); 
        $url = $uri->toString(); 
        $url = strtok($url, '?');
        
        
            $user =& JFactory::getUser();
            $user_eid = $user->get('username'); //This SHOULD be EID
            $user_name = $user->get('name');
            $user_email = $user->get('email');
        
        $body   = "Attention!  A Content change has been made on". $config->get( 'sitename' ).
                  "\n URL:".$url.
                  "\nUser:" .$user_name."\n".
                  "EID: " . $user_eid."\n".
                  "E-mail: " . $user_email."\n".
                  "Page Title:" . $title. "\n"
                  ."To stop receiving this e-mail please contact webmaster@cns.utexas.edu\n"
                  ."E-mail generated by Custom Plugin developed by CNS Web Team: 'Email Notification on Change'";  
        $subject = "Alert!  Change on: ". $config->get( 'sitename' );
        
        $to = array("email1@email.com", "email2@email.com");
        //set it all
        $mailer =& JFactory::getMailer();
		$mailer->setSender('email@email.com'); //from the person requesting access
		$mailer->addRecipient($to);
		$mailer->setSubject($subject);
		$mailer->setBody($body);
		$sent = $mailer->Send();
        
        if($sent !== true){
        JError::raiseNotice( 100, 'ERROR SENDING EMAIL TO COMMUNICATIONS COORDINATOR.' );    
        }
        else{
        JError::raiseNotice( 100, 'Communications Coordinator notified of changes.' );    
        }                
    }
}